(TeX-add-style-hook
 "partisan_gap"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "12pt" "letterpaper")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("appendix" "titletoc" "title") ("xcolor" "usenames" "dvipsnames" "svgnames" "table") ("geometry" "margin=1in") ("hyperref" "linkcolor=blue" "			colorlinks=true" "			urlcolor=blue" "			pdfstartview={XYZ null null 1.00}" "			pdfpagemode=UseNone" "			citecolor={bluish}" "			pdftitle={partisan_gap}") ("multibib" "resetlabels" "labeled") ("fontenc" "T1") ("mathdesign" "bitstream-charter") ("cleveref" "nameinlink" "capitalize" "noabbrev") ("caption" "hang" "font=small" "skip=0pt" "labelfont={bf}")))
   (TeX-run-style-hooks
    "latex2e"
    "../tabs/treatment_labels"
    "."
    "../tabs/mturk_hk_mc_likert"
    "./sections/appendix"
    "article"
    "art12"
    "appendix"
    "color"
    "booktabs"
    "xcolor"
    "geometry"
    "hyperref"
    "multibib"
    "natbib"
    "float"
    "graphicx"
    "amsfonts"
    "amssymb"
    "amsbsy"
    "amsxtra"
    "verbatim"
    "setspace"
    "sectsty"
    "pdflscape"
    "fancyhdr"
    "url"
    "fullpage"
    "multirow"
    "rotating"
    "fontenc"
    "mathdesign"
    "chngcntr"
    "longtable"
    "adjustbox"
    "dcolumn"
    "cleveref"
    "footmisc"
    "caption"
    "subcaption"
    "lscape")
   (TeX-add-symbols
    "bch"
    "ying"
    "bgcd"
    "ech"
    "phantomcaption"
    "citeapos"
    "sym")
   (LaTeX-add-labels
    "sec:theory"
    "sec:inflationary_measures"
    "sec:data"
    "txt:IDA"
    "txt:CUD"
    "txt:FSR"
    "txt:IMC"
    "fig:partisangaps-mturk"
    "eq:partisangap-mturk"
    "tab:partisangaps-mturk"
    "fig:partisangaps-mturk-reg"
    "sec:partisan_cues"
    "fig:yougov-reg"
    "eq:pgap-yougov"
    "tab:partisangaps-yougov"
    "fig:partisangaps-texas-unemp"
    "tab:partisangaps-texas-unemp"
    "tab:partisangaps-texas-fedtax"
    "sec:confidence_coding"
    "fig:mturk_hk"
    "sec:discussion")
   (LaTeX-add-bibliographies
    "pgap"))
 :latex)

